export const FILL_CONTACTS = 'FILL_CONTACTS'
export const FILL_CONVERSATIONS = 'FILL_CONVERSATIONS'

export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_GROUP_NAME = 'SET_GROUP_NAME'
export const SET_GROUP_USERS = 'SET_GROUP_USERS'
export const SET_NAVBAR_OPTION = 'SET_NAVBAR_OPTION'
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const TYPE_MESSAGE_INPUT = 'TYPE_MESSAGE_INPUT'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_GROUP = 'CREATE_GROUP'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION'

export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const SUBMIT_AUTH = 'SUBMIT_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const VALIDATE_AUTH = 'VALIDATE_AUTH'
export const SET_USER_VALIDATE = 'SET_USER_VALIDATE'

export const TOOGLE_EMOJI_PIKER = 'TOOGLE_EMOJI_PIKER'
